name: Build and Deploy Docker image
on:
 push:
  tags:
   "*"
env:
 AWS_REGION: ap-south-1
 ECR_REPOSITORY: 533267288970.dkr.ecr.ap-south-1.amazonaws.com/prototypes/base-server
 IMAGE_TAG: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        run: |
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REPOSITORY:$IMAGE_TAG
            echo "IMAGE $IMAGE_TAG is pushed to $ECR_REPOSITORY"
            echo "image_tag=$IMAGE_TAG" 
            echo "full_image=$ECR_REPOSITORY:$IMAGE_TAG"  
